package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * AppartientId generated by hbm2java
 */
public class AppartientId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1494947669891526451L;
	private int numq;
	private int numcd;
	private int nums;

	public AppartientId() {
	}

	public AppartientId(int numq, int numcd, int nums) {
		this.numq = numq;
		this.numcd = numcd;
		this.nums = nums;
	}

	public int getNumq() {
		return this.numq;
	}

	public void setNumq(int numq) {
		this.numq = numq;
	}

	public int getNumcd() {
		return this.numcd;
	}

	public void setNumcd(int numcd) {
		this.numcd = numcd;
	}

	public int getNums() {
		return this.nums;
	}

	public void setNums(int nums) {
		this.nums = nums;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppartientId))
			return false;
		AppartientId castOther = (AppartientId) other;

		return (this.getNumq() == castOther.getNumq())
				&& (this.getNumcd() == castOther.getNumcd())
				&& (this.getNums() == castOther.getNums());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumq();
		result = 37 * result + this.getNumcd();
		result = 37 * result + this.getNums();
		return result;
	}

}
