package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Appartient generated by hbm2java
 */
public class Appartient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AppartientId id;
	private Integer rang;

	public Appartient() {
	}

	public Appartient(AppartientId id) {
		this.id = id;
	}

	public Appartient(AppartientId id, Integer rang) {
		this.id = id;
		this.rang = rang;
	}

	public AppartientId getId() {
		return this.id;
	}

	public void setId(AppartientId id) {
		this.id = id;
	}

	public Integer getRang() {
		return this.rang;
	}

	public void setRang(Integer rang) {
		this.rang = rang;
	}

}
