package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AssisteId generated by hbm2java
 */
public class AssisteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5573124488029433620L;
	private int nume;
	private Date datea;
	private int heurea;

	public AssisteId() {
	}

	public AssisteId(int nume, Date datea, int heurea) {
		this.nume = nume;
		this.datea = datea;
		this.heurea = heurea;
	}

	public int getNume() {
		return this.nume;
	}

	public void setNume(int nume) {
		this.nume = nume;
	}

	public Date getDatea() {
		return this.datea;
	}

	public void setDatea(Date datea) {
		this.datea = datea;
	}

	public int getHeurea() {
		return this.heurea;
	}

	public void setHeurea(int heurea) {
		this.heurea = heurea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssisteId))
			return false;
		AssisteId castOther = (AssisteId) other;

		return (this.getNume() == castOther.getNume())
				&& ((this.getDatea() == castOther.getDatea()) || (this
						.getDatea() != null && castOther.getDatea() != null && this
						.getDatea().equals(castOther.getDatea())))
				&& (this.getHeurea() == castOther.getHeurea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNume();
		result = 37 * result
				+ (getDatea() == null ? 0 : this.getDatea().hashCode());
		result = 37 * result + this.getHeurea();
		return result;
	}

}
