package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Assiste generated by hbm2java
 */
public class Assiste implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7554931635060103252L;
	private AssisteId id;
	private Integer nbfautes;

	public Assiste() {
	}

	public Assiste(AssisteId id) {
		this.id = id;
	}

	public Assiste(AssisteId id, Integer nbfautes) {
		this.id = id;
		this.nbfautes = nbfautes;
	}

	public AssisteId getId() {
		return this.id;
	}

	public void setId(AssisteId id) {
		this.id = id;
	}

	public Integer getNbfautes() {
		return this.nbfautes;
	}

	public void setNbfautes(Integer nbfautes) {
		this.nbfautes = nbfautes;
	}

}
