package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Cd generated by hbm2java
 */
public class Cd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -834272133907945507L;
	private Integer numcd;
	private String editeur;

	public Cd() {
	}

	public Cd(String editeur) {
		this.editeur = editeur;
	}

	public Integer getNumcd() {
		return this.numcd;
	}

	public void setNumcd(Integer numcd) {
		this.numcd = numcd;
	}

	public String getEditeur() {
		return this.editeur;
	}

	public void setEditeur(String editeur) {
		this.editeur = editeur;
	}

}
