package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Eleve generated by hbm2java
 */
public class Eleve implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3874393060225172223L;
	private Integer nume;
	private String nom;
	private String prenom;
	private String adresse;
	private Date datenaiss;

	public Eleve() {
	}

	public Eleve(String nom, String prenom, String adresse, Date datenaiss) {
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.datenaiss = datenaiss;
	}

	public Integer getNume() {
		return this.nume;
	}

	public void setNume(Integer nume) {
		this.nume = nume;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Date getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(Date datenaiss) {
		this.datenaiss = datenaiss;
	}
	@Override
    public String toString() {
        return "Elever [nume=" + nume + ", Nom =" + nom
                + ", Prenom=" + prenom + ", adresse=" + adresse + ", date="
                + datenaiss + "]";
    }  
}
