package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExamenId generated by hbm2java
 */
public class ExamenId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 405429939289219865L;
	private Date datee;
	private int heuree;

	public ExamenId() {
	}

	public ExamenId(Date datee, int heuree) {
		this.datee = datee;
		this.heuree = heuree;
	}

	public Date getDatee() {
		return this.datee;
	}

	public void setDatee(Date datee) {
		this.datee = datee;
	}

	public int getHeuree() {
		return this.heuree;
	}

	public void setHeuree(int heuree) {
		this.heuree = heuree;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExamenId))
			return false;
		ExamenId castOther = (ExamenId) other;

		return ((this.getDatee() == castOther.getDatee()) || (this.getDatee() != null
				&& castOther.getDatee() != null && this.getDatee().equals(
				castOther.getDatee())))
				&& (this.getHeuree() == castOther.getHeuree());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDatee() == null ? 0 : this.getDatee().hashCode());
		result = 37 * result + this.getHeuree();
		return result;
	}

}
