package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InscritId generated by hbm2java
 */
public class InscritId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8914069002706155929L;
	private int nume;
	private Date datee;
	private int heuree;

	public InscritId() {
	}

	public InscritId(int nume, Date datee, int heuree) {
		this.nume = nume;
		this.datee = datee;
		this.heuree = heuree;
	}

	public int getNume() {
		return this.nume;
	}

	public void setNume(int nume) {
		this.nume = nume;
	}

	public Date getDatee() {
		return this.datee;
	}

	public void setDatee(Date datee) {
		this.datee = datee;
	}

	public int getHeuree() {
		return this.heuree;
	}

	public void setHeuree(int heuree) {
		this.heuree = heuree;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InscritId))
			return false;
		InscritId castOther = (InscritId) other;

		return (this.getNume() == castOther.getNume())
				&& ((this.getDatee() == castOther.getDatee()) || (this
						.getDatee() != null && castOther.getDatee() != null && this
						.getDatee().equals(castOther.getDatee())))
				&& (this.getHeuree() == castOther.getHeuree());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNume();
		result = 37 * result
				+ (getDatee() == null ? 0 : this.getDatee().hashCode());
		result = 37 * result + this.getHeuree();
		return result;
	}

}
