package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Inscrit generated by hbm2java
 */
public class Inscrit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7350555697597356878L;
	private InscritId id;
	private Integer nbfautes;

	public Inscrit() {
	}

	public Inscrit(InscritId id) {
		this.id = id;
	}

	public Inscrit(InscritId id, Integer nbfautes) {
		this.id = id;
		this.nbfautes = nbfautes;
	}

	public InscritId getId() {
		return this.id;
	}

	public void setId(InscritId id) {
		this.id = id;
	}

	public Integer getNbfautes() {
		return this.nbfautes;
	}

	public void setNbfautes(Integer nbfautes) {
		this.nbfautes = nbfautes;
	}

}
