package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Moniteur generated by hbm2java
 */
public class Moniteur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4358819700217606220L;
	private int numm;
	private String nom;
	private String prenom;

	public Moniteur() {
	}

	public Moniteur(int numm) {
		this.numm = numm;
	}
	public Moniteur(String nom, String prenom) {
		this.nom = nom;
		this.prenom = prenom;
	}
	public Moniteur(int numm, String nom, String prenom) {
		this.numm = numm;
		this.nom = nom;
		this.prenom = prenom;
	}

	public int getNumm() {
		return this.numm;
	}

	public void setNumm(int numm) {
		this.numm = numm;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}
	@Override
    public String toString() {
        return "Moniteur [numm=" + numm + ", Nom =" + nom
                + ", Prenom=" + prenom + "]";
    } 
}
