package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5182241780906262522L;
	private Integer numq;
	private String intitule;
	private String reponse;
	private Integer diffic;
	private String theme;

	public Question() {
	}

	public Question(String intitule, String reponse, Integer diffic,
			String theme) {
		this.intitule = intitule;
		this.reponse = reponse;
		this.diffic = diffic;
		this.theme = theme;
	}

	public Integer getNumq() {
		return this.numq;
	}

	public void setNumq(Integer numq) {
		this.numq = numq;
	}

	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

	public Integer getDiffic() {
		return this.diffic;
	}

	public void setDiffic(Integer diffic) {
		this.diffic = diffic;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

}
