package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Seance generated by hbm2java
 */
public class Seance implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2281021654891039781L;
	private SeanceId id;
	private Integer nums;
	private Integer numcd;

	public Seance() {
	}

	public Seance(SeanceId id) {
		this.id = id;
	}

	public Seance(SeanceId id, Integer nums, Integer numcd) {
		this.id = id;
		this.nums = nums;
		this.numcd = numcd;
	}

	public SeanceId getId() {
		return this.id;
	}

	public void setId(SeanceId id) {
		this.id = id;
	}

	public Integer getNums() {
		return this.nums;
	}

	public void setNums(Integer nums) {
		this.nums = nums;
	}

	public Integer getNumcd() {
		return this.numcd;
	}

	public void setNumcd(Integer numcd) {
		this.numcd = numcd;
	}

}
