package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * SerieId generated by hbm2java
 */
public class SerieId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7547247353966348849L;
	private int nums;
	private int numcd;

	public SerieId() {
	}

	public SerieId(int nums, int numcd) {
		this.nums = nums;
		this.numcd = numcd;
	}

	public int getNums() {
		return this.nums;
	}

	public void setNums(int nums) {
		this.nums = nums;
	}

	public int getNumcd() {
		return this.numcd;
	}

	public void setNumcd(int numcd) {
		this.numcd = numcd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SerieId))
			return false;
		SerieId castOther = (SerieId) other;

		return (this.getNums() == castOther.getNums())
				&& (this.getNumcd() == castOther.getNumcd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNums();
		result = 37 * result + this.getNumcd();
		return result;
	}

}
