package com.model;
// Generated 1 févr. 2015 11:00:11 by Hibernate Tools 3.4.0.CR1

/**
 * Serie generated by hbm2java
 */
public class Serie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4552550474146330690L;
	private SerieId id;

	public Serie() {
	}

	public Serie(SerieId id) {
		this.id = id;
	}

	public SerieId getId() {
		return this.id;
	}

	public void setId(SerieId id) {
		this.id = id;
	}
	
	public boolean equals(Object obj)
	{
		Serie tmp = (Serie) obj;
		if( tmp instanceof Serie)
		{
			if((this.getId().getNums() == tmp.getId().getNums()) && (this.getId().getNumcd() == tmp.getId().getNumcd()))
			    return true;
		}
		return false;
		
	}

}
